#Should enable shader support? (For changing the ambience volume when holding a torch)
shadersupport.value=false
#Play the ambience also during the day?
ambienceatdayandnight.value=false
#How long/smooth should the transition be (in decibels)? (Smaller = Slower)
#Range: 0.01 ~ 2.0
volumestep.value=0.75
#How long should the delay per step be (in seconds)?
#Range: 0.1 ~ 2.0
delaystep.value=0.5
